namespace ScrabbleTowers.Engine
{
    public class Games
    {
        public static Game Polish = new Game("Polish", new[]
        {
            new Letter('a'),
            new Letter('a'),
            new Letter('a', LetterColor.Green),
            new Letter('a', LetterColor.Red),
            new Letter('b', LetterColor.Green),
            new Letter('c', LetterColor.Yellow),
            new Letter('d'),
            new Letter('d', LetterColor.Red),
            new Letter('e'),
            new Letter('e'),
            new Letter('e', LetterColor.Yellow),
            new Letter('g', LetterColor.Green),
            new Letter('i'),
            new Letter('i'),
            new Letter('i', LetterColor.Yellow),
            new Letter('j'),
            new Letter('k'),
            new Letter('k', LetterColor.Green),
            new Letter('l'),
            new Letter('l', LetterColor.Red),
            new Letter('ł'),
            new Letter('m'),
            new Letter('m', LetterColor.Green),
            new Letter('n'),
            new Letter('n', LetterColor.Red),
            new Letter('o'),
            new Letter('o'),
            new Letter('o', LetterColor.Red),
            new Letter('p'),
            new Letter('p', LetterColor.Yellow),
            new Letter('r'),
            new Letter('r', LetterColor.Red),
            new Letter('s'),
            new Letter('s'),
            new Letter('t'),
            new Letter('t', LetterColor.Yellow),
            new Letter('u'),
            new Letter('u'),
            new Letter('w', LetterColor.Red),
            new Letter('y'),
            new Letter('y'),
            new Letter('z'),
            new Letter('z', LetterColor.Yellow),
        });
    }
}